name: Deploy (dev)
on:
    push:
        branches:
            - dev

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: 'dev'

jobs:
    QC:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout ğŸ›ï¸
              uses: actions/checkout@master
              with:
                  persist-credentials: false

            - name: Use Node.js 20.x
              uses: actions/setup-node@v3
              with:
                  node-version: 20.x
                  cache: 'npm'

            - name: Install ğŸ”§
              run: |
                  npm install
                  npm run build-gql

            - name: QC ğŸ—ï¸
              run: |
                  npm run lint
                  npm run tsc

    deploy:
        needs: QC
        runs-on: ubuntu-latest
        environment:
            name: deploy-staging # TODO change env name later
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            - name: Checkout ğŸ›ï¸
              uses: actions/checkout@master
              with:
                  persist-credentials: false

            - name: Use Node.js 20.x
              uses: actions/setup-node@v3
              with:
                  node-version: 20.x
                  cache: 'npm'

            - name: Install ğŸ”§
              run: |
                  npm install
                  npm run build-gql

            - name: Set up AWS CLI
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ap-southeast-2

            - name: Deploy Back end
              run: npm run deploy -- --require-approval never
              working-directory: ./packages/quizard-cdk

            - name: Build Web
              run: WEB_BASE_URL="/quizard/" npm run build
              working-directory: ./packages/quizard-web

            - name: Setup Pages
              uses: actions/configure-pages@v3

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v2
              with:
                  # Upload dist repository
                  path: './packages/quizard-web/dist'

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v2
